# Generated by Django 5.1 on 2026-01-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('preferred_name', models.CharField(blank=True, max_length=100)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=22)),
                ('application_type', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('guardian_name', models.CharField(blank=True, max_length=150)),
                ('guardian_email', models.EmailField(blank=True, max_length=254)),
                ('guardian_phone', models.CharField(blank=True, max_length=30)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_email', models.EmailField(blank=True, max_length=254)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=30)),
                ('stake_district_mission', models.CharField(max_length=200)),
                ('ward_branch', models.CharField(max_length=200)),
                ('bishop', models.CharField(blank=True, max_length=150)),
                ('medical_info', models.TextField(blank=True)),
                ('dietary_info', models.TextField(blank=True)),
                ('requires_attention', models.CharField(blank=True, max_length=250)),
                ('tshirt_size', models.CharField(blank=True, max_length=10)),
                ('agreed_terms_text', models.TextField(blank=True)),
                ('group', models.CharField(blank=True, help_text='FSY group assignment (e.g. Group A, Group 1)', max_length=50)),
                ('room', models.CharField(blank=True, help_text='Room assignment (e.g. Room 101)', max_length=50)),
            ],
        ),
    ]
