# Generated by Django 5.1 on 2026-02-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='stake_district_mission',
            field=models.CharField(choices=[('cebu_city_stake', 'Cebu City Stake'), ('cebu_central_stake', 'Cebu Central Stake'), ('bogo_district', 'Bogo District')], max_length=50),
        ),
    ]
