# Generated by Django 5.1 on 2026-02-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_alter_participant_stake_district_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='agree_to_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='application_type',
            field=models.CharField(choices=[('participant', 'Participant'), ('counselor', 'Counselor'), ('assistant_coordinator', 'Assistant Coordinator'), ('coordinator', 'Coordinator')], default='participant', max_length=100),
        ),
        migrations.AlterField(
            model_name='participant',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
